const ORDER_STATUSES = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  COMMITMENT_PAID: 'COMMITMENT_PAID',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  PICKED_UP: 'PICKED_UP',
  BALANCE_PAID: 'BALANCE_PAID',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  REFUNDED: 'REFUNDED',
};

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DISPATCHER: 'DISPATCHER',
};

const DELIVERY_TYPES = {
  HOME_DELIVERY: 'HOME_DELIVERY',
  PICKUP_STATION: 'PICKUP_STATION',
};

const PAYMENT_TYPES = {
  COMMITMENT_ONLINE: 'COMMITMENT_ONLINE',
  REMAINING_CASH: 'REMAINING_CASH',
};

const PAYMENT_PROVIDERS = {
  MOCK: 'MOCK',
  FLUTTERWAVE: 'FLUTTERWAVE',
  MTN_MOMO: 'MTN_MOMO',
  AIRTEL_MONEY: 'AIRTEL_MONEY',
  CASH: 'CASH',
};

const FOOD_UNITS = [
  'kg',
  'bunch',
  'crate',
  'litre',
  'piece',
  'pack',
  'sack',
  'basket',
];

/**
 * Centralized, server-controlled order status transition map.
 * Clients (customers AND admins) may never set statuses arbitrarily:
 * every transition must appear as a value in this map.
 * Terminal states (COMPLETED, CANCELLED, REFUNDED) intentionally have no exits.
 */
const ORDER_STATUS_TRANSITIONS = {
  PENDING_PAYMENT: ['COMMITMENT_PAID', 'CANCELLED', 'PAYMENT_FAILED'],
  COMMITMENT_PAID: ['CONFIRMED', 'CANCELLED'],
  CONFIRMED: ['PREPARING', 'CANCELLED'],
  PREPARING: ['READY_FOR_DELIVERY', 'READY_FOR_PICKUP', 'CANCELLED'],
  READY_FOR_DELIVERY: ['OUT_FOR_DELIVERY'],
  READY_FOR_PICKUP: ['PICKED_UP'],
  OUT_FOR_DELIVERY: ['DELIVERED', 'DELIVERY_FAILED'],
  DELIVERED: ['BALANCE_PAID'],
  PICKED_UP: ['BALANCE_PAID'],
  BALANCE_PAID: ['COMPLETED'],
  COMPLETED: [],
  CANCELLED: [],
  PAYMENT_FAILED: ['CANCELLED', 'PENDING_PAYMENT'],
  DELIVERY_FAILED: ['REFUNDED', 'OUT_FOR_DELIVERY'],
  REFUNDED: [],
};

/**
 * Statuses from which a CUSTOMER may cancel their own order.
 * Admins use the full transition map (CANCELLED is reachable from more states).
 */
const CUSTOMER_CANCELLABLE_STATUSES = ['PENDING_PAYMENT', 'COMMITMENT_PAID', 'CONFIRMED'];

/**
 * Customer-facing order statuses (admin-only operational states are excluded)
 */
const CUSTOMER_VISIBLE_STATUSES = [
  'PENDING_PAYMENT',
  'COMMITMENT_PAID',
  'CONFIRMED',
  'PREPARING',
  'READY_FOR_DELIVERY',
  'READY_FOR_PICKUP',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'PICKED_UP',
  'BALANCE_PAID',
  'COMPLETED',
  'CANCELLED',
];

module.exports = {
  ORDER_STATUSES,
  ROLES,
  DELIVERY_TYPES,
  PAYMENT_TYPES,
  PAYMENT_PROVIDERS,
  FOOD_UNITS,
  ORDER_STATUS_TRANSITIONS,
  CUSTOMER_CANCELLABLE_STATUSES,
  CUSTOMER_VISIBLE_STATUSES,
};
